---

ansible_user: wayne

## - network
## .   Networking related configuration
## .   These values are used to configure an external DNS provider with
## .   netplan.
network:
  dns:
    - 192.168.86.1
    - 4.2.2.1
    - 8.8.8.8


k3s:
  version: v1.21.3+k3s1
  master_ip: "{{ hostvars[groups['master'][0]]['ansible_ssh_host'] | default(groups['master'][0]) }}"
  disable_svc: "local-storage,servicelb,traefik"
  extra_server_args: ""
  extra_agent_args: ""
  data_dir: "/var/lib/rancher/k3s"

systemd_dir: /etc/systemd/system

sshd:
  service_name: sshd
  service_config: /etc/ssh/sshd_config

##
## - required_pkgs:
## .   Packages required for this Playbook to run.
## .   Please don't remove them.
##
required_pkgs:
  - golang-cfssl

etcd:
  version: v3.5.0
  ##
  ## cluster_token:
  ## .  In order to create the initial cluster we need to define a token.
  ##    update only if you want to recreate your custer
  ##
  cluster_token: "etcd-cluster-01"
  data_dir: "/var/lib/etcd"
  ##
  ## initial_nodes:
  ## .  Update this variable to configure the initial custer nodes.
  ##
  initial_nodes: "node-1=https://192.168.86.191:2380,node-2=https://node-2:2380,node-3=https://node-3:2380"
  ##
  ## data_store_endpoint:
  ## .  Define nodes where k3s must connect to make use of etcd.
  data_store_endpoint: "https://192.168.86.191:2379,https://node-2:2379,https://node-3:2379"
  ##
  ## data_dir:
  ## .  Directory where TLS certificates are generated and stored.
  ##
  initial_ca_dir: "/etc/etcd/tls"
  ##
  ## cluster health configuration:
  ##
  election_timeout: 5000
  heartbeat_interval: 250
  ##
  ## ca_lock_file:
  ##    Change only if you know what you're doing!.
  ##    The Ansible CA lockfile prevents playbooks to regenerate the TLS certificates
  ##    required for etcd to connect.
  ##
  ##    Remove this file and run Playbooks again if you wish this behavior, otherwise
  ##    keep it safe and don't remove it.
  ##
  ##    A new one will be created in the next Ansble run in case it doesn't exist.
  ##
  ca_lock_file: "/root/ansible-ca.lock"
  ##
  ## CA:
  ##   CA certificate configuration.
  ##
  CA:
    cert:
      CN: "CA"
      key:
        algo: rsa
        size: 2048
    expiration: 43800h
  ##
  ## client:
  ##   etcd peer certificate configuration.
  ## . Those certificates are used by etcd and k3s process to join a new node to the clluster.
  ##
  client:
    cert:
      CN: "{{ inventory_hostname }}"
      key:
        algo: rsa
        size: 2048

extra_pkgs:
  - lm-sensors
  - tcpdump
  - sysstat


nfs:
  nfs_exports: ["/SRV/NFS/kubedata 192.168.86.0/24(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)"]